apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRNdwpNVE0xTlRGYUZ3MDBNekEwTVRNd01UTTFOVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFESjZ1d1B5bTQ3ZW5ud2dRK3drLzQrMWtodlovQ2JzWDBJWlZ1ZENPQlN4RmVIUS9McgpUTVIvWjhkVkczUSt6L3dpYm1EcjNubUNrZDZ5VWlDZHdCY3ZkZS9BZzM5QXliS0NMcnYwbTFJRXRObmphc1BRCm5GK24xVnFDQkZFNjBqWWtzdWNsaUI0NUdsWVdaOE94c2NEOHBJcmg0ZHBaN3pPSi9la1pjYWwvaVVhZ1QvcXoKTUdBbjluRUpxdzNKUlhDZklhM0pvYzR0Qzd2WWhWaVp3NDhJTmtEMCtwVk1hc0RWY29MN1VoVC9ObkI4NFU3bQo0NmVGdXNKZzI1RHI3Y2MrbGhxRFZRV3dSM2ovazVVcjVBQWFIUklPcCtwVG92a3NWNUtVUS9jL1VYTFpONkFaCnFUM0VrYzVDcGhEUXdjOTF1dGJXS2ZaR3NzdGxRa2dGSWlkaEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJFOXl6N28xNUNCYUxqYzM2NQo2LzNPOXBMY1dEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmMHhMM0MxSmxUeVJRSG9BdXVVSWRoTUpNb2RDCjBhdjRwU3Rhci84TmRITHBVckNkaW1vQk5FNEFhNmJjczB4bGdEMjRzUW4rcTNUM1QxRzlDdEh4NFFyYzV0a0wKU1NhVTlObkZqVXQ2ZGpCWDBiWWQwZXRCdERGTnlCL2FFbzQ5dk9sZmhOQ3BSd29nVzhTSFpBb2ZhZ1ZDRHQyRgpnSmJPV0hlVEhvMUJJK0ZyOUpYNFFPVzdLeFpNdG93b1pVTWRGNSs3Qm5jUi9nU2RmR3VLK203Nk44anVWRExOCkVpOGEvZXFXSlB6Rm95TTN4Mnp3NEIwUGJkK2YzakpZL0Vrekc2T3hucEJKREZsV1doU3cvZFFNcE4xeklBUTEKdS9BQ0tBZEc4VjRxRG1MWjVQYUpoY0ZSNnhnZThUYzRqWWFoeWtSbFBpV1VqUHdudmFYcjNlbHkzZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://7220e2a3-79ed-40e1-9885-b0fca999e757.k8s.ondigitalocean.com
  name: do-nyc3-k8s
contexts:
- context:
    cluster: do-nyc3-k8s
    user: do-nyc3-k8s-admin
  name: do-nyc3-k8s
current-context: do-nyc3-k8s
users:
- name: do-nyc3-k8s-admin
  user:
    token: dop_v1_10e4e06f32fdff746023a9a8e7263f2057732cf366abeb8ac6eba6df62d9bbba
